---
username: admin
password: admin

banner_text: | 
              ---------------Welcome to BIGIP-----------------
              UNAUTHORIZED ACCESS TO THIS DEVICE IS PROHIBITED
              You must have explicit, authorized permission to access or configure this device.
              Unauthorized attempts and actions to access or 
              use this system may result in civil and/or criminal penalties.
              All activities performed on this device are logged and monitored.

hostname: 'adc01.lab.local'

license_key: 'xxxxx-xxxxx-xxxxx-xxxxx-xxxxx'

ntp_servers:
  - '0.ca.pool.ntp.org'
  - '1.ca.pool.ntp.org'

dns_servers:
  - '8.8.8.8'

dns_search_domains:
  - 'local'
  - 'localhost'
  - 'lab.local'

ip_version: 4

bind_servers:
  - '8.8.8.8'
  - '4.4.4.4'

# only uncomment if tagged interfaces are supposed to be configured.
# tagged_vlan:
#   - name: 'one-arm'
#     interface: '1.1'
#     tag: '4000'

# only uncomment if untagged interfaces are supposed to be configured.
untagged_vlan:
  - name: 'one-arm'
    interface: '1.1'
  - name: 'north'
    interface: '1.2'
  - name: 'south'
    interface: '1.3'

selfip_information:
  - name: 'one-arm'
    address: '192.168.189.254'
    netmask: '255.255.255.0'
    vlan: 'one-arm'
    allow_service: 'default'
  - name: 'north'
    address: '172.16.1.254'
    netmask: '255.255.255.0'
    vlan: 'north'
    allow_service: 'default'
  - name: 'south'
    address: '172.16.100.254'
    netmask: '255.255.255.0'
    vlan: 'south'
    allow_service: 'default'

module_provisioning:
  # - name: 'apm'
  #   level: 'nominal'
  - name: 'gtm'
    level: 'nominal'

routes:
#############################################
# Routes towards Northbound External Networks
  # - network: '0.0.0.0/0' - For URI based you have to put the cidr in the network and remove the mask argument.
  - network: 0.0.0.0
    mask: '0'
    gw: '172.16.1.1'
    name: 'Defaul_Route' # No Space in the name
    description: Default
    partition: 'Common'

#############################################
mgmt_routes:
  # - network: '172.24.2.0'
  #   mask: '255.255.255.0'
  #   gw: '172.10.10.1'
  #   name: 'NetOps_RA_VPN' # No Space in the name
  #   description: Default_To be deleted
  #   partition: 'Common'